### ISSUE TITLE
Tests do not run 

### ISSUE THREAD

**Issue by ghost** [maiha/hq.cr#3]
Just tried to run `crystal spec` on master after installing deps.
```
In src/hq/css/none.cr:1:1

 1 | struct Hq::Css::None
     ^
Error: abstract `def Enumerable(T)#each(& : (T ->))` must be implemented by Hq::Css::None
```

**Comment by maiha** [comment]
Hi, @yujiri8 

This library is no longer maintained because something wonderful has come along.

Please try to use kostya's lexbor. 👍 
https://github.com/kostya/lexbor

**Comment by ghost** [comment]
Sorry, don't know how I missed that. I guess I had two repositories open at once and I got confused about which one had the deprecation notice.
